language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
env:
  - NODESCREENSHOT_SHOW=1
node_js:
  - '6'
  - 'node'
before_install:
  - npm i -g yarn --cache-min 999999999
install:
  - yarn
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start +extension RANDR;
script:
  - yarn test
sudo: false
addons:
  apt:
    packages:
    - libcairo2
    - libfreetype6
    - libfontconfig1
    - libxcomposite1
    - libasound2
    - libxdamage1
    - libxext6
    - libxfixes3
    - libnss3
    - libnspr4
    - libexpat1
    - libudev0
